const MONOLITH_URL = process.env.BASE_URL || "http://localhost:3000";

export const SERVICE_URLS = {
  LOCATION: MONOLITH_URL,
  IMAGE: MONOLITH_URL,
  AUTH: MONOLITH_URL,
  TRIP: MONOLITH_URL,
  PLACES: MONOLITH_URL,
  FOOD: MONOLITH_URL,
  WEATHER: MONOLITH_URL,
};